radarlabs/react-native-radar

ios/RNRadarUtils.m

Add missing `@` sign before at using string at method placesProviderForString

Missing `@` sign for string

---

ios/RNRadarUtils.m

Fix the typo preventing it from building

---

android/build.gradle
android/src/main/java/io/radar/react/RNRadarUtils.java
ios/RNRadarUtils.m

Version bump + adding new event field

Update SDK to 2.1+

---

package.json

Changes:
- Fixes #54  and #61.
- Add `ERROR_RATE_LIMIT` to iOS error parsing.
- Ensure main queue method calls for iOS module.

2.1.3 release

---

package.json
react-native-radar.podspec

Based on #60:
- Adds podspec for automatically including transitive dependencies with CocoaPods
- Bump version to 2.1.4

Add podspec for CocoaPods users

---

README.md

From https://radar.io/documentation/sdk#android-background

Add background tracking explanation to README.md

---

package-lock.json

- https://github.com/radarlabs/react-native-radar/network/alert/package-lock.json/minimist/open
-

cve minimist

---

package-lock.json

https://github.com/radarlabs/react-native-radar/network/alerts

missing update

---

package-lock.json
package.json

https://trello.com/c/2uDpZKyw/771-cve-braces-react-native-radar-231

cve upgrade braces 2.3.x

---

package-lock.json
package.json

- https://trello.com/c/yXgXWksA/770-cve-logkitty-071-react-native-radar
- https://github.com/radarlabs/react-native-radar/network/alert/package-lock.json/logkitty/open

logkitty gh alert 072020

---

android/src/main/java/io/radar/react/RNRadarUtils.java

see https://github.com/radarlabs/react-native-radar/issues/124

allow for Float types in mapToJson

---

android/build.gradle
package.json

Point at https://github.com/radarlabs/radar-sdk-android/releases/tag/3.1.11

Bump version

---

.circleci/config.yml
android/build.gradle
android/src/main/java/io/radar/react/RNRadarModule.java
example/ios/Example/Info.plist
example/ios/Podfile.lock
example/metro.config.js
ios/RNRadar.m
package-lock.json
package.json
react-native-radar.podspec

- Adds `NOT_DETERMINED` permissions state on iOS and Android
- Bumps versions
- Adds back `Podfile.lock` and updates `metro` config for example app

Add NOT_DETERMINED permissions state

---

.circleci/config.yml
android/build.gradle
android/src/main/java/io/radar/react/RNRadarModule.java
example/App.js
ios/RNRadar.h
ios/RNRadar.m
js/index.js
package.json

Support promises for permission requests like
```
Radar.requestPermissions(false).then((result) => {
// called after permission prompt dismissed, or immediately if prompt not shown
});
```

Permission callbacks

---

.github/ISSUE_TEMPLATE.md
README.md
android/build.gradle
ios/Cartfile.resolved
package.json
react-native-radar.podspec

@tjulien - can we add this to 3.2.1 to support the fraud context type?

upgrade native sdks to 3.2 latest

---

android/src/main/java/io/radar/react/RNRadarModule.java
example/App.js
example/android/app/src/main/java/io/radar/example/MainApplication.java
example/ios/Example/AppDelegate.m
ios/RNRadar.m
js/index.native.js
package.json

For: https://linear.app/radarlabs/issue/MOB-60/expose-initialize-in-the-react-native-sdk
Attempting to pull this into a sample app to test

Expose initialize function

---

android/build.gradle
ios/Cartfile.resolved
package-lock.json
package.json
react-native-radar.podspec

Exposing `geometryRadius` & `geometryCenter` for geofences and `location`for places

Bump to 3.5.10

---

android/build.gradle
ios/Cartfile.resolved
package-lock.json
package.json
react-native-radar.podspec

iOS to 3.5.12
Android to ~~3.5.13~~ 3.5.12
Web SDK to 3.6.0

Bump to 3.5.12

---

js/index.native.js

Makes the `3.8.5` release non-breaking

Fix initialize

---

android/build.gradle
ios/Cartfile.resolved
package-lock.json
package.json
react-native-radar.podspec

Bump RN to 3.8.8, iOS to 3.8.6, Android to 3.8.9

Bump to 3.8.8

---

android/build.gradle
android/src/main/java/io/radar/react/RNRadarModule.java
ios/Cartfile.resolved
ios/RNRadar.m
package-lock.json
package.json
react-native-radar.podspec

Version bump to 3.10.5

---

src/@types/RadarNativeInterface.ts
src/index.native.ts

update isTracking() type

---

README.md
hooks/pre-commit

checks App.*, so it'll work for App.js and App.web.js, and also work once we change it to App.tsx

add pre-commit hook

---

example/App.tsx
example/android/app/build.gradle
example/app.json
example/ios/Example.xcodeproj/project.pbxproj
example/ios/Podfile
example/ios/Podfile.lock
example/package-lock.json
example/package.json
ios/RNRadar.m
package.json

all the diffs are in package.lock + Podfile.lock, so it's actually not that scary

Expo plugin maps

---

android/build.gradle
android/src/main/java/io/radar/react/RNRadarModule.java
ios/RNRadar.m
package-lock.json
package.json

android build: https://expo.dev/accounts/radarlabs/projects/waypoint/builds/93d5dc3b-80e7-46b6-a04f-3c6e684c5ef6

Revert android permission changes

---

src/ui/map.jsx

the RN native Map component doesn't read styles in correctly as map options nor default to styles set in the dashboard

fix RN Map component
