radarlabs/react-native-radar

android/src/main/java/com/onradar/react/RNRadarPackage.java

Fixed crashed when compile with RN > 0.47+
Related discussion 
https://github.com/react-native-community/react-native-blur/pull/226

Remove deprecated Android package override

---

android/src/main/java/com/onradar/react/RNRadarUtils.java
ios/RNRadarUtils.h
ios/RNRadarUtils.m

Seeing that the native modules were returning `event.alternatePlaces` already, it was really straightforward to add methods which add the `alternatePlaces` array to the event being returned to the react-native event emitter. I have tested this for both iOS and Android and seems to work properly. This resolves issue #20.

Add alternate places support to events

---

ios/RNRadar.xcodeproj/project.pbxproj
ios/RNRadarUtils.m

We are not using cocoapods or carthage in our products and I noticed that following the manual installation instructions in radar.io documentation failed with the react-native component.
This PR fixes that allowing for the SDK to be placed inside the `ios` folder.
This also fixes a typo in a method call to `arrayForAlternatePlaces` in `RNRadarUtils`.

Fixes a Typo and adds the possibility to manually add the SDK to iOS

---

android/build.gradle

Android module is built dynamically so we need to expose transitive deps with `api` rather than `implementation`

Fix dependency declaration

---

android/src/main/java/io/radar/react/RNRadarModule.java
android/src/main/java/io/radar/react/RNRadarUtils.java
ios/RNRadar.m
ios/RNRadarUtils.h
ios/RNRadarUtils.m
js/index.js

This allows users to apply the new options like so:
```js
Radar.startTracking({
sync: 'all', // or 'possibleStateChanges'
offline: 'replayStopped' // or 'replayOff'
})
```

Expose the new RadarTrackingOptions from SDK 2.1

---

.circleci/config.yml
ios/.npmignore
ios/RNRadar.xcodeproj/project.pbxproj
package.json
react-native-radar.podspec

- Removes `.npmignore` for `ios` directory, therefore adding tests to npm package

Release 2.1.5

---

ios/RNRadar.xcodeproj/project.pbxproj
package.json

Addresses #69 : 
- Adds default `ios/` directory to framework and header search paths, so the native module can find the linked `RadarSDK.framework`

Release 2.1.7

---

.circleci/config.yml
android/build.gradle
android/src/main/java/io/radar/react/RNRadarModule.java
android/src/main/java/io/radar/react/RNRadarUtils.java
android/src/test/java/io/radar/react/RNRadarModuleTest.java
android/src/test/java/io/radar/react/RNRadarUtilsTest.java
ios/RNRadar.m
ios/RNRadarTests/RNRadarTests.m
js/index.js
package.json
test/index.test.js

- Added api for [`setMetadata()`](https://radarlabs.github.io/radar-sdk-ios/Classes/Radar.html#/c:objc(cs)Radar(cm)setMetadata:)
- Added `priority` option for `startTracking()` that corresponds to Android [`RadarTrackingPriority`](https://radarlabs.github.io/radar-sdk-android/io/radar/sdk/Radar.RadarTrackingPriority.html), has no effect on iOS. 
- accepted values are `efficiency` and `responsiveness`

Api updates

---

package-lock.json

- not 100% on if we also need to update this:
- https://github.com/radarlabs/react-native-radar/blob/master/example/yarn.lock#L876

cve logkitty 0.7.1

---

.github/workflows/radar-release-actions.yml

As documented here: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry

github action to create react-native-radar SDK releases

---

.github/workflows/update-native-sdks.yml
android/build.gradle.template
ios/Cartfile.resolved.template
react-native-radar.podspec.template

Add Github Action that automates:
- updating `build.gradle` for Android SDK version bumps
- updating `Cartfile.resolved` + `react-native-radar.podspec` for iOS SDK version bumps
- updating `package.json` and `package-lock.json`

[9522] Add workflow to automate SDK version bumps

---

.github/workflows/update-native-sdks.yml

[Expressions in Github actions](https://docs.github.com/en/actions/learn-github-actions/expressions#literals
) need to use single quotes. See issue [here](https://github.com/actions/runner/issues/866).
Swapped out all double quotes in the `update-native-sdks.yml` file for consistency

[Automation | SC-9522] Fix Github Actions

---

.github/workflows/update-native-sdks.yml

The `npm version` in the auto-version bump Github action was failing because, by default, `npm version` makes a commit and creates a tag. 
Fortunately, these [options can be bypassed](https://docs.npmjs.com/cli/v7/commands/npm-version#git-tag-version) so these changes can just be included with the PR's changes.

[Automation] Triage Version-bump Github Action

---

android/build.gradle
android/src/main/java/io/radar/react/RNRadarModule.java
example/App.js
example/ios/Example.xcodeproj/project.pbxproj
example/ios/Podfile.lock
example/package.json
example/yarn.lock
ios/Cartfile.resolved
ios/RNRadar.m
package-lock.json
package.json
react-native-radar.podspec
test/index.test.js

- Upgrades `radar-sdk-js` to 3.5.0
- Upgrades `radar-sdk-ios` and `radar-sdk-android` to 3.5.9
- Bumps `react-native-radar` version to 3.5.8 to enable us to push out a new release when we're ready (Instructions [here](https://www.notion.so/radarlabs/How-to-release-the-React-Native-SDK-21c70f16e0bd4fe28425923645cadda0))
- Add support for the new `startTrip` with `trackingOptions` param

Upgrade radar-sdk-js, radar-sdk-android and radar-sdk-ios

---

example/metro.config.js
package.json

Fixes MOB-88.
Our metro configuration for our sample app is currently broken (`Error: Unable to resolve module react-native-radar`). This fixes it.

Fix example app metro config

---

.circleci/config.yml
android/build.gradle
ios/Cartfile.resolved
ios/RNRadar.m
package-lock.json
package.json
react-native-radar.podspec

I initially was fixing with a change to `RadarTripOptions.m`, but figured that isolating the changes to just react native would be best.
I've confirmed the change via Waypoint. It now works with `arrivalTime.getTime()` as we had in the example in this repo, as well as `arrivalTime.toIsoString()` which was undocumented but working on Android.
As far as I can, both Android and iOS handle both datetime formats now, but I'll put through some reps on an Android build over the weekend to triple confirm.

Update scheduledArrivalAt handling on iOS

---

.github/workflows/radar-pre-release-actions.yml
.github/workflows/radar-release-actions.yml
package-lock.json
package.json
scripts/check-beta-tag.cjs
scripts/check-latest-tag.cjs

Presently our github actions release pre-releases as `latest`. These changes ensure that beta / pre-releases get marked as such so that `npm install react-native-radar` only installs the latest, non beta versions.

Fix github release process

---

android/build.gradle
ios/Cartfile.resolved
package-lock.json
package.json
react-native-radar.podspec

Tests won't pass until new native SDKs hit their package managers.

3.8.9, bump iOS to 3.8.7, android to 3.8.10

---

js/ui/map.jsx
package-lock.json
package.json

The map element requests location for the location indicator, but we can't be sure that we have the necessary permissions.
The `react-native-radar` sdk doesn't do full permission monitoring, so the safest thing to do is to attempt to get the location and fail gracefully.
I'm presently `console.warn`-ing, but we probably should replicate the [logger](https://github.com/radarlabs/radar-sdk-js/blob/master/src/logger.ts) used in the js sdk sometime soon.

Catch Map element possible permissions error

---

android/build.gradle
android/gradle.properties
android/src/main/java/io/radar/react/RNRadarModule.java
ios/Cartfile.resolved
ios/RNRadar.m
js/index.native.js
package-lock.json
package.json
react-native-radar.podspec

This PR exposes endpoints so that RN SDK can easily access the versioning of the RN SDK and also the underlying native SDK from code.
There are 2 new endpoints:
- `nativeSdkVersion` 
- `rnSdkVersion`
A notable change is that the explicit definition of the versioning of the Android native SDK had been moved from `build.gradle` to `gradle.property`
QA:
we call both of these endpoints in waypoint to determine the versioning of the dependencies 
Android:
IOS:

implemented endpoints for getting versioning for RN and native

---

android/build.gradle
android/src/main/java/io/radar/react/RNRadarModule.java
ios/RNRadar.m
js/index.native.js
package-lock.json
package.json

- Wrapper for setAndroidNotification settings
- Bump version
- IOS wrapper for `setForegroundOptions` and `setAndroidNotificationOptions` now takes a dictionary such that they are truly no-ops rather than crashing upon called on ios.

Wrapper for setAndroidNotificationOptions

---

android/build.gradle
android/src/main/java/io/radar/react/RNRadarModule.java
ios/Cartfile.resolved
ios/RNRadar.m
package-lock.json
package.json
react-native-radar.podspec
test/index.test.js

This PR changes the `expandUnits` param for autocomplete to `mailable`. Value of `true` is passed in for Android wrapper since there are no default value params in Java. Verified by testing using Waypoint

expandUnits -> mailable

---

.circleci/config.yml

QA: CI is correctly flagging the wrong type that is in master right now. https://app.circleci.com/pipelines/github/radarlabs/react-native-radar/1430/workflows/dd445600-b65c-4b97-9819-e8e6c099524a/jobs/3997

add a ci typing step

---

src/@types/RadarNativeInterface.ts
src/@types/types.ts
src/index.native.ts

- Make `Radar.initialize` have optional second param.
- Add `iconString` and `iconColor` fields to `RadarTrackingOptionsForegroundService`

Typing fixes

---

android/build.gradle
android/src/main/java/io/radar/react/RNRadarModule.java
ios/RNRadar.m
package-lock.json
package.json
src/index.ts
tsconfig.json

The previous upgrade to TS introduced a bug that affected projects on older versions of expo using JS. It appears that just loading the import of `radar-js-sdk` into the js layer was causing issues. This PR introduces a fix to prevent that from occuring.

Fix for JS projects

---

android/build.gradle
android/src/main/java/io/radar/react/RNRadarModule.java
ios/Cartfile.resolved
ios/RNRadar.m
package-lock.json
package.json
react-native-radar.podspec

ignore branch name, shouldn've been remote-sdk-config

bump version 3.15.0 using sdk version 3.16.0

---

android/src/main/java/io/radar/react/RNRadarModule.java

`Radar.requestPermissions(true)` broke underneath us, still not full sure of the rationale and the Android change that caused this. 
This new implementation fixes the issue.

fix for requesting bg permissions on android

---

Radar.podspec
android/build.gradle
android/src/newarch/java/com/radar/RadarModule.kt
android/src/oldarch/java/com/radar/RadarModule.java
ios/RNRadar.mm
package-lock.json
package.json
src/@types/types.ts

- updates `radar-ios` dependency to `3.23.1`
- updates `radar-android` dependency to `3.23.2`
- adds optional `categories` to `RadarAddress` 
- bumps `react-native-radar` to `3.22.1`

Add `categories` to RadarAddress 

---

android/src/newarch/java/com/radar/RadarModule.kt
android/src/oldarch/java/com/radar/RadarModule.java
copyAssets.sh
example/App.tsx
example/package-lock.json
ios/RNRadar.mm
package-lock.json
package.json
src/@types/types.ts
src/index.tsx
src/ui/map.jsx
src/ui/map.tsx
src/version.ts
tsconfig.json

- Add onDidFinishLoadingMap event forwarding
- Add onWillStartLoadingMap event forwarding
- Add onDidFailLoadingMap event forwarding
- Update TypeScript definitions for new events
- Maintains existing mapOptions API pattern
- Fixes issue where loading events were ignored
Resolves customer request for onDidFinishLoadingMap support
**New Architecture**
**Old Architecture**

feat: add MapLibreGL loading events to Radar Map component

---

.circleci/config.yml
example/package-lock.json

- Updates `resource_class` to `xlarge`
- Removes memory limits from `GRADLE_OPTS` 
- Sets `ANDROID_NDX_MAX_PARALLEL_JOBS` to 2 
Failing CI 
Fixed CI

FENCE-2485 Fix Android CI job

---

example/App.tsx
example/package-lock.json
example/tsconfig.json
src/@types/types.ts
src/ui/map.jsx

- Adds `showUserLocation` parameter to `mapOptions`: defaults to true 
- Adds `jsx` flag to example `tsconfig` 
**Testing**
iOS old architecture `showUserLocation: true`
iOS new architecture `showUserLocation: false`
Android old architecture `showUserLocation: true`
Android new architecture `showUserLocation: false`

FENCE-2502: Add optional showUserLocation param to mapOptions
